
[dimensions]

	[dimensions.nether]
		#Should nether generate as in default world type? [default: false]
		default = false

		[dimensions.nether.structures]
			#Use only if 'enabled' is true!
			#Should nether fortress be disabled? [default: false]
			disable-fortress = false
			#Should structures like fortresses or bastions be generated in nether? [default: true]
			enabled = true
			#Use only if 'enabled' is true!
			#Should bastions be disabled? [default: true]
			disable-bastions = true

	[dimensions.end]
		#Should end generate as in default world type? [default: false]
		default = false
		#Should structures like end cities be generated in nether? [default: false]
		#This also affects the large islands with chorus plants.
		#Small islands will still be generated.
		structures = false
		#Should the main island be generated as normal? [default: true]
		main-island = false

	[dimensions.overworld]
		#Should structures like end portal or villages be generated in overworld? [default: false]
		structures = true
		#Should the stronghold with end portal be the only structure?
		#Needs default config be 'true', otherwise it'll be ignored. [default: false]
		stronhold-only = true

[spawn]
	#Direction the player should look at initial spawn
	#Allowed Values: NORTH, EAST, SOUTH, WEST
	direction = "SOUTH"
	#Height of the bottom layer from the structure.
	#This affects where exactly the island will be generated.
	#Range: 1 ~ 255
	height = 1

[inventory]
	#Should players' items be dropped when leaving a team? [default: true]
	drop = true
	#Should all items be reset on first world join? [default: false]
	#This will delete all the items given on spawn from other mods guide books.
	clear = false

[utility]
	#Should players be able to create their own team? [default: false]
	create-own-team = false
	#Should players be able to teleport to their home island? [default: true]
	home = true

	[utility.spawns]
		#The range from island center for possible spawns to add. [default: 50]
		#Range: > 0
		range = 50
		#Should players be able to modify their spawn positions? [default: false]
		modify-spawns = false

